Update youtube

diff --git a/youtube b/youtube
--- a/youtube
+++ b/youtube
@@ -1,4 +1,37 @@
 #!/bin/bash
 #youtube thumbnail
 #http://img.youtube.com/vi/youtube-video-id/maxresdefault.jpg
-wget http://img.youtube.com/vi/${1}/maxresdefault.jpg
+#wget http://img.youtube.com/vi/${1}/maxresdefault.jpg
+
+# Script to download YouTube thumbnail using video ID or URL
+
+# Function to extract video ID from YouTube URL
+extract_video_id() {
+  local url=$1
+  local video_id
+
+  # Check if input is a full URL or just the video ID
+  if [[ $url =~ ^https?://(www\.)?youtube\.com/watch\?v=([a-zA-Z0-9_-]{11}) ]]; then
+    video_id=${BASH_REMATCH[2]}
+  elif [[ $url =~ ^https?://youtu\.be/([a-zA-Z0-9_-]{11}) ]]; then
+    video_id=${BASH_REMATCH[1]}
+  elif [[ $url =~ ^[a-zA-Z0-9_-]{11}$ ]]; then
+    video_id=$url
+  else
+    echo "Invalid YouTube URL or video ID"
+    exit 1
+  fi
+
+  echo $video_id
+}
+
+# Get the input parameter (either full URL or video ID)
+input=$1
+
+# Extract video ID from input
+video_id=$(extract_video_id "$input")
+
+# Download the YouTube thumbnail using the extracted video ID
+wget http://img.youtube.com/vi/${video_id}/maxresdefault.jpg
+
+echo "Downloaded thumbnail for video ID: $video_id"
